### ISSUE TITLE
I have this issue since yesterday and I need some help

### ISSUE THREAD

**Issue by Temposchwelle** [andrewsegas/instaboost#15]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x ] I have searched for other issues with the same problem.

## Hosting
- [ x] Is it a local machine?

#### Select one:
- [] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10 Home
## Running Mode
- [ ] instaboost.exe
- [ x] example.py , mode 0?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / 3

## Description

I have this problem since yesterday and I hope that somebody can help me. I didn't change anything and I never got this Error before so I am pretty clueless.

```
Traceback (most recent call last):
  File "C:\Users\??????\Desktop\instaboost-master\instaboost\example.py", line 52, in <module>
    UI = False)
  File "C:\Users\??????\Desktop\instaboost-master\instaboost\src\instabot.py", line 242, in __init__
    self.login()
  File "C:\Users\??????\Desktop\instaboost-master\instaboost\src\instabot.py", line 303, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Program Files\Python35\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Program Files\Python35\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by andrewsegas** [comment]
Hi, i need more details to help, can you paste here your example.py (**BE CAREFUL, HIDE YOUR PASSWORD AND LOGIN**). looking your error looks like you made some wrong changes

**Comment by RhaegarTargaryen55** [comment]
i have the same trouble

**Comment by Temposchwelle** [comment]
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time


from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol
#from src import ihm





bot = InstaBot(
    login="????????",
    password="????????????",
    like_per_day=1850,
    `comments_per_day=900,`
    tag_list=['fotografie', 'photographyislifee', 'photographysouls', 'photographylover', 'photography', 'photographer'], #l: for location, check example in readme.md
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=60,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great, would love if you could check out my stuff too :)", "super ,would love if you could check out my stuff too :)", "good ,would love if you could check out my stuff too :)", "very good ,would love if you could check out my stuff too :)", "good ,would love if you could check out my stuff too :)", "wow ,would love if you could check out my stuff too :)",
                   "WOW ,would love if you could check out my stuff too :)", "cool ,would love if you could check out my stuff too :)", "GREAT ,would love if you could check out my stuff too :)","magnificent ,would love if you could check out my stuff too :)", "magical ,would love if you could check out my stuff too :)",
                   "very cool ,would love if you could check out my stuff too :)", "stylish ,would love if you could check out my stuff too :)", "beautiful ,would love if you could check out my stuff too :)", "so beautiful ,would love if you could check out my stuff too :)",
                   "so stylish ,would love if you could check out my stuff too :)", "so professional ,would love if you could check out my stuff too :)", "lovely ,would love if you could check out my stuff too :)",
                   "so lovely ,would love if you could check out my stuff too :)", "very lovely ,would love if you could check out my stuff too :)", "glorious ,would love if you could check out my stuff too :)","so glorious ,would love if you could check out my stuff too :)",
                   "very glorious ,would love if you could check out my stuff too :)", "adorable ,would love if you could check out my stuff too :)", "excellent ,would love if you could check out my stuff too :)", "amazing ,would love if you could check out my stuff too :)"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
       'sex','follow', 'follower', 'gain', '.id', '_id',
    ],
    unfollow_whitelist=[''],
    UI = False)



while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)
    if  bot.login_status == False:
        break

    if mode == 0:
        bot.new_auto_mod()
    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)
    else:
        print("Wrong mode!")

```

**Comment by roviraleix** [comment]
I'm getting exactly the same error and also from 2 days ago, with my 2 accounts.

**Comment by rogersimon** [comment]
Hi, having the same issue.
Been this way for the past 2 days, with the .exe.

Same thing happens with Instabot apparently, and some fixes have been suggested in this thread:
https://github.com/instabot-py/instabot.py/issues/1287

**Comment by andrewsegas** [comment]
Guys, i didn't get this error, is difficult to help!
I tried today and instaboost is running as usual. Do u have any idea or things different that could make me get this error to help you?

**Comment by Temposchwelle** [comment]
I didn't change anything and I also tried to redownload everything but still same error. 
And I also when I start it now I get before Login : exception on check version

**Comment by andrewsegas** [comment]
this check version is because my vm is out... but it's not the problem.
I'll try to change something to get this error, i'll tell when i have some news
any questions or news let me know. 
thanks

**Comment by Temposchwelle** [comment]
@rogersimon I tried the instabot version with the fix that they got in the thread and that fix is working...but it is not working in the instaboost version

**Comment by bootexe** [comment]
I've got the same issue since yesterday too 😕
seems instagram change protocol ?

**Comment by rogersimon** [comment]
They changed their cookie policy, which seemed to be causing this issue on instabot.
@andrewsegas does it speak to you when you check the adapted code on the thread I linked to?
Thanks!

**Comment by rogersimon** [comment]
@andrewsegas I know what might be a difference between you and us: they might have updated their cookie policy just for users connecting from the European Union (due to GDPR), so if you could make it look like you were connecting from the EU (VPN?), this might work out fine.

**Comment by mrleyz** [comment]
@andrewsegas so did you find the problem ? Will you commit a new version ?

**Comment by andrewsegas** [comment]
Guys, I really want to help, but I don't have this error, may someone with this error call me inbox, in my e-mail to help me, if i face this error I'll be able to understand and fix it.
Have you tried to use a different network? Try to use different wifi or computer, because I checked today and it works.

**Comment by mrleyz** [comment]
I rebooted it, i tried with wifi and 4G and it still doesn't work, so this is the error that came up : 
<img width="1183" alt="capture d ecran 2018-06-14 a 12 46 46" src="https://user-images.githubusercontent.com/40164363/41408284-6cc7be18-6fd2-11e8-9045-25b758d3c8fd.png">

My python version is 2.7.14

**Comment by bootexe** [comment]
I know is maybe beacause your not in europe
At this moment a law passed that order to internet website to change there cookie policy
Try to use an european account

**Comment by roviraleix** [comment]
I can avoid the problem using a proxy from Canada or US, when trying from europe the error apears again.Maybe you can ue a proxy fro europe to get the error?

**Comment by bootexe** [comment]
Proxy or VPN ?

**Comment by roviraleix** [comment]
VPN sorry, I'm using Windscribe with location in US or Canada and works fine

**Comment by roviraleix** [comment]
Hello,

any news solving this error? Now I'm having this problem even using a VPN from NewYork, probably they also changed the cookies policy there..

**Comment by andrewsegas** [comment]
Hi, @Temposchwelle and everyone, can you please test again? it should work

**Comment by lordlevi** [comment]
Hi andrew, I also have this problem since Friday. I chechked different networks and different computers windos 7 windows 10 changed insta password but it didn't help me.

Do you know what caused this problem? :)
