### ISSUE TITLE
Login error! Connection error!

### ISSUE THREAD

**Issue by vansprosk8** [andrewsegas/instaboost#16]
I have this prblem:
`Login error! Connection error!`
## Python Version
3

in errors.log:
```
WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last):
  File "site-packages\fake_useragent\utils.py", line 166, in load
  File "site-packages\fake_useragent\utils.py", line 144, in get_browser_versions
fake_useragent.errors.FakeUserAgentError: No browsers version found for Edge/IE
```

**Comment by andrewsegas** [comment]
Please, use the template for issue.
I need to understand some variables
