### ISSUE TITLE
unfollow_whitelist

### ISSUE THREAD

**Issue by omaconer** [andrewsegas/instaboost#22]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
3

## Description
Hi, any clues? 

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/*******/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/*******/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/*******/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
Please man, update your instaboost. We already fixed this bug :D
