### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by focamonca** [andrewsegas/instaboost#23]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?
It's a Raspberry pi3

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux Raspbian

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 and 3

## Description

The same error I got on instabot.py ...
```
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    from src import InstaBot
  File "/home/pi/Projects/instagood/instaboost/instaboost/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/Projects/instagood/instaboost/instaboost/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent

```

**Comment by andrewsegas** [comment]
Please, check this issue https://github.com/andrewsegas/instaboost/issues/4

**Comment by focamonca** [comment]
I followed the steps on #4 but I'm still getting

`raceback (most recent call last):
  File "example.py", line 7, in <module>
    from src import InstaBot
  File "/home/pi/Projects/instagood/instaboost/instaboost/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/Projects/instagood/instaboost/instaboost/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
`

**Comment by focamonca** [comment]
this is what I did 

`pi@raspberrypi:~/Projects/instagood/instaboost/instaboost $ pip install fake_useragent --user
Collecting fake_useragent
Installing collected packages: fake-useragent
Successfully installed fake-useragent-0.1.10
pi@raspberrypi:~/Projects/instagood/instaboost/instaboost $ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fake_useragent
>>> fake_useragent.0.1.10
  File "<stdin>", line 1
    fake_useragent.0.1.10
                   ^
SyntaxError: invalid syntax
>>> fake_useragent.VERSION
u'0.1.10'
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> 
`

**Comment by andrewsegas** [comment]
so, the problem is not about instaboost. Is in your python, please search about the instalation of fake_useragent for your linux version. you need to install fake_useragent and everything will be ok.
when you try in your prompt to code in python "import fake_useragent --VERSION" and you get the version you'll be able to run instaboost

**Comment by andrewsegas** [comment]
don't forget to check about user permission

**Comment by focamonca** [comment]
I already did it
http://prntscr.com/iwj5i0
