### ISSUE TITLE
but doesn't work

### ISSUE THREAD

**Issue by RhaegarTargaryen55** [andrewsegas/instaboost#25]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (0)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
3

## Description

the bot worked fine during 5-6 months, but couple days ago when i tried to run it, i received this:

Traceback (most recent call last):
  File "example.py", line 65, in <module>
    UI = False)
  File "/Users/NoOne/Documents/Instabot/instaboost-master/Instaboost/src/instabot.py", line 173, in __init__
    fake_ua = UserAgent()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

i haven't chanegel any code/text at all.. so it come from nothing.. any ideas?

**Comment by andrewsegas** [comment]
I know, now it is working. Can you try again?
please if you get close this issue.

Thanks

**Comment by RhaegarTargaryen55** [comment]
hey, i just downloaded it again and here is what i get when i run it:


Traceback (most recent call last):
  File "example.py", line 59, in <module>
    UI = False)
  File "/Users/NoOne/Documents/Instabot/instaboost-master/Instaboost/src/instabot.py", line 242, in __init__
    self.login()
  File "/Users/NoOne/Documents/Instabot/instaboost-master/Instaboost/src/instabot.py", line 322, in login
    ui = UserInfo()
  File "/Users/NoOne/Documents/Instabot/instaboost-master/Instaboost/src/userinfo.py", line 30, in __init__
    self.hello()
  File "/Users/NoOne/Documents/Instabot/instaboost-master/Instaboost/src/userinfo.py", line 35, in hello
    main = self.s.get(self.url_list[self.i_a]["main"])
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ink361.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10c37d950>: Failed to establish a new connection: [Errno 60] Operation timed out',))

any ideas what is this?

**Comment by andrewsegas** [comment]
@RhaegarTargaryen55 , Try to Log in your Instagram in your Web Browser and let me know if is possible.

**Comment by RhaegarTargaryen55** [comment]
@andrewsegas just successfully did it right now, so it's possible

**Comment by andrewsegas** [comment]
@RhaegarTargaryen55 I realized just now that you are using MAC, the problem about UserAgent is normal in some MAC version, please, Check in old issues, there are many tips about it, some guys got to solve.
You can try to import again, reinstall and more tips.
