### ISSUE TITLE
cant login to instaboost

### ISSUE THREAD

**Issue by hadadadebadada** [andrewsegas/instaboost#28]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
/ Linux / Debian /  Kali 2019.2

## Running Mode
- [x] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)?
- [x] instaboost.py
- [ ] Other

## Python Version?
3

## Description

Type the description of your issue here.

I cannot login to instaboost in all running modes. 
Can someone offer me help with this issue?

Note: Instabot-py is working fine.

Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    UI = False)
  File "/root/Downloads/instaboost/Instaboost/src/instabot.py", line 242, in __init__
    self.login()
  File "/root/Downloads/instaboost/Instaboost/src/instabot.py", line 305, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by andrewsegas** [comment]
Everything is working fine,
Can you try with the newest version? 
you selected every mode, which one did u get this error?
