### ISSUE TITLE
Connection problem.

### ISSUE THREAD

**Issue by vinci1618** [andrewsegas/instaboost#31]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [ x] I have searched for other issues with the same problem.

## Hosting
- [ x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Running Mode
- [ ] instaboost.exe
- [x ] example.py , mode (1,2,3,4 or 5)?: 1
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / 3 : 2

## Description

Type the description of your issue here.

There is a problem connecting with my credentials but my account is working perfectly. 

```
Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    UI = False)
  File "/Users/jaimemendoza/instaboost/instaboost/src/instabot.py", line 241, in __init__
    self.login()
  File "/Users/jaimemendoza/instaboost/instaboost/src/instabot.py", line 270, in login
    boostversion(self)
  File "/Users/jaimemendoza/instaboost/instaboost/src/boostversion.py", line 10, in boostversion
    r = s.get('http://ec2-18-218-101-210.us-east-2.compute.amazonaws.com:8080/?user='+self.user_login+'&version='+self.boostVersion)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ec2-18-218-101-210.us-east-2.compute.amazonaws.com', port=8080): Max retries exceeded with url: /?user=usertest&version=19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b950a10>: Failed to establish a new connection: [Errno 61] Connection refused',))


```

**Comment by andrewsegas** [comment]
Im sorry everybody, It was MY mistake, now´it will work, Just the Version control was out and without "try - catch".
Try now, and it will work, please close the task if it solved

**Comment by andrewsegas** [comment]
Please update the last commit
5009157e9432c248cd5df24c66c5e547d98772ec
