### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by playfuldreamz** [andrewsegas/instaboost#32]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Running Mode
- [x] instaboost.exe
- [ ] example.py , mode (1,2,3,4 or 5)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / 3
3
## Description

Type the description of your issue here.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 284, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x06556090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /web/likes/1746569070831969771/like/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x06556090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\instabot.py", line 651, in like
  File "site-packages\requests\sessions.py", line 555, in post
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\requests\adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /web/likes/1746569070831969771/like/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x06556090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "src\instabot.py", line 396, in get_media_id_by_tag
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:root:Except on like!
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
  File "http\client.py", line 1331, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
  File "ssl.py", line 1009, in recv_into
  File "ssl.py", line 871, in read
  File "ssl.py", line 631, in read
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 440, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 357, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
  File "http\client.py", line 1331, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
  File "ssl.py", line 1009, in recv_into
  File "ssl.py", line 871, in read
  File "ssl.py", line 631, in read
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\instabot.py", line 651, in like
  File "site-packages\requests\sessions.py", line 555, in post
  File "site-packages\requests\sessions.py", line 508, in request
  File "site-packages\requests\sessions.py", line 618, in send
  File "site-packages\requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

```

**Comment by andrewsegas** [comment]
Im sorry everybody, It was MY mistake, now´it will work, Just the Version control was out and without "try - catch".
Try now, and it will work, please close the task if it solved

**Comment by andrewsegas** [comment]
Please, update the last commit 5009157e9432c248cd5df24c66c5e547d98772ec
