### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by andradjp** [andrewsegas/instaboost#33]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Is it a local machine?
- [x] Raspberry PI
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Linux
## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / 3
2 and 3
## Description
Problem 
Type the description of your issue here.
the problem started after it is upgraded to a recent version, there is a virtual task in AWS
```
Include the contents of the error.log here (if applicable).
```
18:12 Instaboost v2.19.0 started at 30.03.2018 18:12:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x760db7b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ec2-18-218-101-210.us-east-2.compute.amazonaws.com', port=8080): Max retries exceeded with url: /?user=andrade.jp&version=19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x760db7b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    UI = False)
  File "/opt/andrade.jp/instaboost/instaboost/src/instabot.py", line 241, in __init__
    self.login()
  File "/opt/andrade.jp/instaboost/instaboost/src/instabot.py", line 270, in login
    boostversion(self)
  File "/opt/andrade.jp/instaboost/instaboost/src/boostversion.py", line 10, in boostversion
    r = s.get('http://ec2-18-218-101-210.us-east-2.compute.amazonaws.com:8080/?user='+self.user_login+'&version='+self.boostVersion)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ec2-18-218-101-210.us-east-2.compute.amazonaws.com', port=8080): Max retries exceeded with url: /?user=andrade.jp&version=19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x760db7b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by andrewsegas** [comment]
Im sorry everybody, It was MY mistake, now´it will work, Just the Version control was out and without "try - catch".
Try now, and it will work, please close the task if it solved

**Comment by andradjp** [comment]
Work! Thanks

**Comment by andradjp** [comment]
The same problem again =/

**Comment by andrewsegas** [comment]
Please, update the last commit

**Comment by andrewsegas** [comment]
5009157e9432c248cd5df24c66c5e547d98772ec
