### ISSUE TITLE
ImportError: No module named fake_useragent

### ISSUE THREAD

**Issue by russAIC** [andrewsegas/instaboost#5]
This is pulling from the broken branch of instabot. Needs to be fixed :/

```
ais-MacBook-Pro:instaboost russell$ python example.py
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    from src import InstaBot
  File "/Users/russell/instaboost/instaboost/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/russell/instaboost/instaboost/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
```

**Comment by andrewsegas** [comment]
I tried on mac and is everything ok, check permissions, or anyway, try to run

```py
pip install fake_useragent --user
```

try to write

```py
import fake_useragent 
```
and check if it is installed

**Comment by russAIC** [comment]
my man!

**Comment by andrewsegas** [comment]
@russAIC did you get? what was the problem? Maybe we have another user with the same problem :)
