### ISSUE TITLE
seems that something went wrong this morning

### ISSUE THREAD

**Issue by FlavianoMucedda** [andrewsegas/instaboost#8]
> Fill in all requirements *before* submitting an issue.

- [] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC high sierra
## Running Mode
- [ ] instaboost.exe
- [x] example.py , mode (1,2,3,4 or 5)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2.710

## Description

Everything went fine yesterday but since this morning it seems that some features aren't working.

The bot is stuck at 400 likes since yesterday et now it runs connect perfectly and then stop i don't know why...

```
raceback (most recent call last):
  File "example.py", line 105, in <module>
    bot.new_auto_mod()
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/instabot.py", line 783, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/instabot.py", line 872, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/feed_scanner.py", line 56, in feed_scanner
    likers_graber_protocol(self)
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
```

**Comment by FlavianoMucedda** [comment]
so seems that the big error message came from using mode 2, so i went back to mode 0 everything seems to work except the like who are still like this : 

Trying to like: 1763762170914390387
11:49 Not liked: 400

**Comment by FlavianoMucedda** [comment]
ad it seems that because of that the bot just pause itself and doesn't do anything

**Comment by andrewsegas** [comment]
Hi man.
As I see nothing changed in instagram schema, I tried to check and here it works.
Try to check if you are temporarily banned, just checking if you can like photos in your cellphone

**Comment by FlavianoMucedda** [comment]
that's weird... the first 2 hours i got the bug i was still able to like pic manually but now it seems i can't like it by myself either...

**Comment by andrewsegas** [comment]
Yeh, wait some hours and try again, try to use something around 1500 likes per day after that.

**Comment by FlavianoMucedda** [comment]
ok thanks mate :)
Do you recommend lo let the bot running(like on a raspberry pi) or it's better to put a starting and end time?

**Comment by andrewsegas** [comment]
@FlavianoMucedda start and end time, but is always good if is possible, take a look sometimes to check if everything is ok or you got the like error, in this case just stop the bot wait some hours and start again.

**Comment by FlavianoMucedda** [comment]
it was indeed a softban everything worked fine this morning... but a few minut ago something else happened and it's a whole other bug... this is the error rapport.. : 

Traceback (most recent call last):
  File "example.py", line 63, in <module>
    UI = False)
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/instabot.py", line 242, in __init__
    self.login()
  File "/Users/admin/Desktop/instaboost-master/Instaboost/src/instabot.py", line 302, in login
    r = self.s.get(self.url)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1100f6790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
